# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:


    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd" #"imagick"

    filter_sets:
        cache: ~
        desktop_banner_image:
            quality: 70
            png_compression_level: 7
            filters:
                resize: { size: [2560, 500] }

        four_cols_full_image:
            quality: 70
            png_compression_level: 7
            filters:
                resize: { size: [1280, 720, mode: outbound ] }

        latest_videos_col_image:
            png_compression_level: 7
            quality: 70
            filters:
                resize: { size: [ 720, 480, mode: outbound ] }

        user_thumb:
            png_compression_level: 7
            quality: 70
            filters:
                resize: { size: [ 128, 128, mode: outbound ] }